### ISSUE TITLE
Importar tabela de produtos CSV / XSLX

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-feed-importer#13]
Colocar campo para importação de arquivos e possibilitar a importação de tabelas de outras plataformas:

Loja Integrada

[PlanilhaLojaIntegrada.csv](https://github.com/ecomplus/app-feed-importer/files/7770713/PlanilhaLojaIntegrada.csv)
![WhatsApp Image 2021-12-23 at 10 33 21](https://user-images.githubusercontent.com/35343551/147274936-2d87997f-e5a3-47dc-abda-03e34d645a98.jpeg)

Nuvem

[produtos (1).csv](https://github.com/ecomplus/app-feed-importer/files/7770719/produtos.1.csv)

**Comment by leomp12** [comment]
> importação de tabelas de outras plataformas

\* De outra**S** não, vamos escolher um modelo de tabela, que pode ser igual ao de uma outra plataforma comum, e aí suportar o upload de tabelas nesse modelo (completas ou não)...

**Comment by leomp12** [comment]
meio tarde @matheusgnreis 😬 
comentei com o @thiagoabreudev mas não sei se é viável mudar agora, talvez depois.
de qualquer forma a tabela de exemplo aí da nuvem parace incompleta, não? pouquíssimas colunas...

**Comment by matheusgnreis** [comment]
Eu acho que ela foi feita pra ser assim simples mesmo.

**Comment by leomp12** [comment]
uai mas do jeito que está aí ela na verdade é muito limitada, não só simples 😛
