### ISSUE TITLE
Upload de arquivo com erro

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-feed-importer#19]
Não está sendo possível fazer o POST. 
Na URL de HOST está localhost:5001, possivelmente ai está o erro
![image](https://user-images.githubusercontent.com/35343551/150697155-2b739c26-16ba-4b8b-95a5-ec99fad92dc2.png)

**Comment by matheusgnreis** [comment]
@thiagoabreudev @leomp12

**Comment by leomp12** [comment]
"Possivelmente" 🤣

**Comment by leomp12** [comment]
Só que o issue é do marketplace na verdade...
@thiagoabreudev consegue ver isso aí com urgência?
