### ISSUE TITLE
Erro na importação do arquivo

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-feed-importer#21]
Aparentemente no processo da conversão do arquivo
![image](https://user-images.githubusercontent.com/35343551/150859388-8ef0fd24-aa89-484b-91c6-8379cbe283b4.png)

**Comment by matheusgnreis** [comment]
Template padrão 
[template.csv](https://github.com/ecomplus/app-feed-importer/files/7933896/template.csv)
Arquivo enviado
[casaedesign.csv](https://github.com/ecomplus/app-feed-importer/files/7933897/casaedesign.csv)
Ambos deram o mesmo erro

**Comment by thiagoabreudev** [comment]
https://github.com/ecomplus/admin-marketplace/pull/209
