### ISSUE TITLE
Importar feeds de produtos no padrão GMC

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-feed-importer#8]
**Is your feature request related to a problem? Please describe.**
Precisamos de um app que importe em fila os produtos de feeds XML no padrão do GMC ([especificação de produto](https://support.google.com/merchants/answer/7052112?hl=en)) para facilitar migração de lojas menores (sem ERPs) de outras plataformas.

**Describe the solution you'd like**
Parsear o XML e importar as entries (itens) em fila assíncronamente usando Pub/Sub, salvando na Store API. 

**Describe alternatives you've considered**
N/A

**Additional context**
- Referência do GMC em https://support.google.com/merchants/answer/7052112?hl=en
- Engenharia reversa de https://github.com/ecomplus/products-feed/blob/master/lib/main.php
- Implementação da importação deve ser parecida com a dos ERPs como https://github.com/ecomplus/app-tiny-erp/blob/master/functions/lib/integration/parsers/product-to-ecomplus.js (https://github.com/ecomplus/app-tiny-erp/blob/master/functions/lib/integration/import-product.js#L158-L170)

**Comment by leomp12** [comment]
@GankSir (não te consigo assinar aqui ainda 😐 )

**Comment by leomp12** [comment]
@matheusgnreis @ricardocici as plataformas não costumam gerar esses XMLs do jeito certo, então é bom termos exemplos para prever edge cases e se necessário criar tratamentos diferentes para cada plataforma de origem, se (ou quando) vocês tiverem colem aqui por favor o URL do XML da loja e nome da respectiva plataforma.

**Comment by matheusgnreis** [comment]
@leomp12 aparentemente o que fiquei sabendo ai por agências, outras plataformas estão utilizando o modelo https://support.google.com/merchants/answer/160589?hl=pt que seria o 2.0, talvez tenha isso de diferença para o nosso. De toda forma aqui, já solicitei alguns parceiros para nos disponibilizar

**Comment by leomp12** [comment]
@matheusgnreis "que seria o 2.0" não, na verdade não existe um feed do GMC 2.0, isso é só sobre a formatação do feed XML (Atom 0.3/1.0 ou RSS 1.0/2.0), a especificação do objeto produto (cada item do feed) segue sendo a mesma e definida pelo GMC em https://support.google.com/merchants/answer/7052112?hl=en .

Não especifiquei o formato do feed XML no issue porque o app deve suportar ambos (tanto Atom quanto RSS), e também já tinha comentado isso na call com o @thiagoabreudev e @GankSir .

**Comment by thiagoabreudev** [comment]
@leomp12 @matheusgnreis , encontrei esses 2 exemplos na doc do google

- https://github.com/ecomplus/app-feed-importer/blob/master/functions/test/example_feed_xml_atom.xml
- https://github.com/ecomplus/app-feed-importer/blob/master/functions/test/example_feed_xml_rss.xml

seria isso aqui mesmo?

**Comment by leomp12** [comment]
@thiagoabreudev como tá em inglês eu acho que você pegou um exemplo do Google né? É isso mas no cenário real (brasileiro principalmente) as coisas não vão estar 100% de acordo com o ideal haha
Quero dizer, na prática os XMLs das plataformas vão ter informações faltando e gambiarras que teríamos que contornar prograssivamente.

**Comment by matheusgnreis** [comment]
https://lojasereiarte.com.br/google_shopping.xml/

**Comment by matheusgnreis** [comment]
Loja integrada ainda não consegui saber o padrao q emitem la

**Comment by leomp12** [comment]
https://github.com/ecomplus/app-feed-importer/commit/c7942676ddd5f5654b4f699e63d1e43c993fca4b
